# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
logo: /assets/icons/ChinarClose.jpg
title: Chinar Mehta
email: chinar.dac@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    Hi, I am Chinar. I am a Fulbright Fellow at Carnegie Mellon University and a Ph.D. scholar at the Department of Communication at the University of Hyderabad. I am interested in interdisciplinary research about technology - its cultures, and histories. With previous work experience as a front-end developer, as a media researcher, I am largely interested in the web as a communication channel.    
description1: 
    My doctoral research is about how knowledge-in-practice is inscribed on web interfaces - for which I draw theory from Science & Technology Studies, Feminist Cultural Studies of Science, and New Media Studies. In other words, I follow web developers & managers around and ask them to explain what they do (and how they do it) in great detail.
description2:
    I was also part of FemLab.co, a research project that aims to understand the communicative practices of women workers in India and Bangladesh so that digital tools can be leveraged for their collectivization. 
description3:
    I channel my energies into creative ways to get research to a broader audience - through media productions like documentary films, podcasts, radio, and others. You can reach me at chinar [dot] dac [at] gmail [dot] com.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
remote_theme: pages-themes/minimal
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
